[project]
name = "avito-nlp"
version = "0.1.0"
description = "Кандидатогенерация для категории услуг Авито (Recall@50)"
requires-python = ">=3.11,<3.13"
dependencies = [
    "pandas>=2.2",
    "pyarrow>=16",
    "numpy>=1.26",
    "scikit-learn>=1.5",
    "bm25s>=0.2",
    "snowballstemmer>=2.2",
    "tqdm>=4.66",
    "ipykernel>=6.29",
    "transformers>=4.41",
    "catboost>=1.2",
    "huggingface-hub>=0.23",
    "torch>=2.14.0",
    "sentence-transformers>=6.1.0",
]
